### **Semana 3: Actividad 1** - *Conceptos de almacenamiento y recuperación de información*

**Iván Lee Cancino - A01793491**

### **TC4029 - Ciencia y Analítica de Datos**

**Prof. Jobish Vallikavungal**

**Prof. Julio César Galindo López**

*04 - Octubre - 2022*

---


---

### **Parte 1: Fundamentos de bases de datos**

**1. Fundamentos de bases de datos para ciencia de datos.** 
 
Los datos son posiblemente el recurso más importante en un proyecto de ciencia de datos. En este contexto, una base de datos se puede definir como un conjunto estructurado de datos almacenados en un medio electrónico (memoria o en la nube) de manera conveniente para que distintos usuarios puedan acceder a ellos.    
En general existen dos tipos de bases de datos dependiendo de la manera en la que la información está organizada: 
- *Base de datos relacional (Relational data base):* los datos o registros se organizan y almacenan en tablas que pueden conectarse entre sí.  

- *Base de datos no-relacional (NoSQL data base):* en este tipo de base de datos la información está conectada por categorías, utilizadas principalmente para datos no estructurados como video o imágenes. 

El acceso y manipulación de los datos se realiza mediante un lenguaje apropiado. Para bases de datos relacionales el más popular es SQL (Structured Query Language).  
 
 
**2. Fundamentos de almacenes de datos (Data Warehouse) para ciencia de datos.** 
 
Un almacén de datos es un sistema centralizado que consolida grandes cantidades de información proveniente de diversas fuentes. Puede contener múltiples bases de datos, y habilita las tareas de gestión y análisis de datos para la toma de decisiones. La información se alimenta de manera regular y con el tiempo se almacenan datos históricos. Como punto importante, los datos se almacenan en formato tabular para favorecer el análisis. 


### **Parte 2: Selección y limpieza de los Datos en Python**

Importamos las librerías para trabajar con el conjunto de datos:

In [1]:
import numpy as np
import pandas as pd

Definimos variable con liga al archivo .csv en github:

In [2]:
input = 'https://raw.githubusercontent.com/PosgradoMNA/Actividades_Aprendizaje-/main/default%20of%20credit%20card%20clients.csv'

La descripcion de la base de datos la podemos ver aqui:
https://raw.githubusercontent.com/PosgradoMNA/Actividades_Aprendizaje-/main/dataset_info.txt

Creamos el conjunto de datos (data frame)

In [3]:
df = pd.read_csv(input)
df 

ID      X1   X2   X3   X4    X5   X6   X7   X8   X9  ...      X15  \
0          1   20000  2.0  2.0  1.0  24.0  2.0  2.0 -1.0 -1.0  ...      0.0   
1          2  120000  2.0  2.0  2.0  26.0 -1.0  2.0  0.0  0.0  ...   3272.0   
2          3   90000  2.0  2.0  2.0  34.0  0.0  0.0  0.0  0.0  ...  14331.0   
3          4   50000  2.0  2.0  1.0  37.0  0.0  0.0  0.0  0.0  ...  28314.0   
4          5   50000  1.0  2.0  1.0  57.0 -1.0  0.0 -1.0  0.0  ...  20940.0   
...      ...     ...  ...  ...  ...   ...  ...  ...  ...  ...  ...      ...   
29995  29996  220000  1.0  3.0  1.0  39.0  0.0  0.0  0.0  0.0  ...  88004.0   
29996  29997  150000  1.0  3.0  2.0  43.0 -1.0 -1.0 -1.0 -1.0  ...   8979.0   
29997  29998   30000  1.0  2.0  2.0  37.0  4.0  3.0  2.0 -1.0  ...  20878.0   
29998  29999   80000  1.0  3.0  1.0  41.0  1.0 -1.0  0.0  0.0  ...  52774.0   
29999  30000   50000  1.0  2.0  1.0  46.0  0.0  0.0  0.0  0.0  ...  36535.0   

           X16      X17      X18      X19      X20     X21      X22     X23  \
0          0.0      0.0      0.0    689.0      0.0     0.0      0.0     0.0   
1       3455.0   3261.0      0.0   1000.0   1000.0  1000.0      0.0  2000.0   
2      14948.0  15549.0   1518.0   1500.0   1000.0  1000.0   1000.0  5000.0   
3      28959.0  29547.0   2000.0   2019.0   1200.0  1100.0   1069.0  1000.0   
4      19146.0  19131.0   2000.0  36681.0  10000.0  9000.0    689.0   679.0   
...        ...      ...      ...      ...      ...     ...      ...     ...   
29995  31237.0  15980.0   8500.0  20000.0   5003.0  3047.0   5000.0  1000.0   
29996   5190.0      0.0   1837.0   3526.0   8998.0   129.0      0.0     0.0   
29997  20582.0  19357.0      0.0      0.0  22000.0  4200.0   2000.0  3100.0   
29998  11855.0  48944.0  85900.0   3409.0   1178.0  1926.0  52964.0  1804.0   
29999  32428.0  15313.0   2078.0   1800.0   1430.0  1000.0   1000.0  1000.0   

         Y  
0      1.0  
1      1.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
29995  0.0  
29996  0.0  
29997  1.0  
29998  1.0  
29999  1.0  

[30000 rows x 25 columns]

Revisamos si existen valores faltantes en la base de datos:

In [4]:
df.isnull().values.any()

True

In [12]:
# Para detectar en que columnas faltan valores: 
df.isnull().any()

ID     False
X1     False
X2      True
X3      True
X4      True
X5      True
X6      True
X7      True
X8      True
X9      True
X10     True
X11     True
X12     True
X13     True
X14     True
X15     True
X16     True
X17     True
X18     True
X19     True
X20     True
X21     True
X22     True
X23     True
Y       True
dtype: bool

**A continuacion trataremos los valores faltantes**

- En caso de existir, eliminaremos las filas con todos los valores faltantes 

In [13]:
# Creamos una copia del conjunto original para trabajar
df2 = df.copy()
# Metodo 'dropna' remueve valores faltantes
df2.dropna(how='all', inplace=True)

- Iniciaremos por la columna **Y:** representa la probabilidad real de que el cliente incumpla con el pago crediticio (1=Si, 0=No).  

In [14]:
# verificamos valores únicos en la columna Y
df2['Y'].unique()

array([ 1.,  0., nan])

Optamos por eliminar las filas con valores nulos.

In [27]:
# usamos parametro 'subset' para seleccionar las columnas deseadas
df2.dropna(inplace=True, subset=['Y'])
df2

ID      X1   X2   X3   X4    X5   X6   X7   X8   X9  ...      X15  \
0          1   20000  2.0  2.0  1.0  24.0  2.0  2.0 -1.0 -1.0  ...      0.0   
1          2  120000  2.0  2.0  2.0  26.0 -1.0  2.0  0.0  0.0  ...   3272.0   
2          3   90000  2.0  2.0  2.0  34.0  0.0  0.0  0.0  0.0  ...  14331.0   
3          4   50000  2.0  2.0  1.0  37.0  0.0  0.0  0.0  0.0  ...  28314.0   
4          5   50000  1.0  2.0  1.0  57.0 -1.0  0.0 -1.0  0.0  ...  20940.0   
...      ...     ...  ...  ...  ...   ...  ...  ...  ...  ...  ...      ...   
29995  29996  220000  1.0  3.0  1.0  39.0  0.0  0.0  0.0  0.0  ...  88004.0   
29996  29997  150000  1.0  3.0  2.0  43.0 -1.0 -1.0 -1.0 -1.0  ...   8979.0   
29997  29998   30000  1.0  2.0  2.0  37.0  4.0  3.0  2.0 -1.0  ...  20878.0   
29998  29999   80000  1.0  3.0  1.0  41.0  1.0 -1.0  0.0  0.0  ...  52774.0   
29999  30000   50000  1.0  2.0  1.0  46.0  0.0  0.0  0.0  0.0  ...  36535.0   

           X16      X17      X18      X19      X20     X21      X22     X23  \
0          0.0      0.0      0.0    689.0      0.0     0.0      0.0     0.0   
1       3455.0   3261.0      0.0   1000.0   1000.0  1000.0      0.0  2000.0   
2      14948.0  15549.0   1518.0   1500.0   1000.0  1000.0   1000.0  5000.0   
3      28959.0  29547.0   2000.0   2019.0   1200.0  1100.0   1069.0  1000.0   
4      19146.0  19131.0   2000.0  36681.0  10000.0  9000.0    689.0   679.0   
...        ...      ...      ...      ...      ...     ...      ...     ...   
29995  31237.0  15980.0   8500.0  20000.0   5003.0  3047.0   5000.0  1000.0   
29996   5190.0      0.0   1837.0   3526.0   8998.0   129.0      0.0     0.0   
29997  20582.0  19357.0      0.0      0.0  22000.0  4200.0   2000.0  3100.0   
29998  11855.0  48944.0  85900.0   3409.0   1178.0  1926.0  52964.0  1804.0   
29999  32428.0  15313.0   2078.0   1800.0   1430.0  1000.0   1000.0  1000.0   

         Y  
0      1.0  
1      1.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
29995  0.0  
29996  0.0  
29997  1.0  
29998  1.0  
29999  1.0  

[29997 rows x 25 columns]

In [28]:
# verificamos
df2['Y'].isnull().values.any()

False

Podemos observar que se eliminaron 3 filas en total.

**Para el resto de las columnas X2 a X23 haremos imputación de valores**

- **X2:** género (1=masculino, 2=femenino). Verificamos que solo existan estos dos valores posibles e imputamos los faltantes con el valor de la moda.


In [29]:
# verificamos valores únicos en la columna
df2['X2'].unique()

array([ 2.,  1., nan])

In [32]:
# imputamos faltantes con la moda
x2mode = df2['X2'].mode()
df2['X2'].fillna(value=x2mode, inplace=True)

df2['X2'].unique()

array([2., 1.])

- **X3:** nivel escolar (1=posgrado, 2=universidad, 3=preparatoria, 4=otros). similar a la columna X2 imputamos el valor de la moda a los faltantes. 

In [33]:
# verificamos valores únicos en la columna
df2['X3'].unique()

array([ 2.,  1.,  3.,  5.,  4.,  6.,  0., nan])

Los valores 0, 5, y 6 no son válidos, por lo que los convertiremos a *NaN* y posteriormente imputaremos el valor de la moda usando solo valores permitidos (1, 2, 3 o 4).

In [34]:
# convertimos a NaN los valores 
N = len(df2['X3'])
for i in range(N):
    if df2.iloc[i, 3] > 4:
        df2.iloc[i, 3] = np.nan 
    elif df2.iloc[i, 3] == 0:
        df2.iloc[i, 3] = np.nan

# verificamos
df2['X3'].unique()

array([ 2.,  1.,  3., nan,  4.])

In [36]:
# imputamos faltantes con la moda
x3mode = df2['X3'].mode()
df2['X3'].fillna(value = x3mode, inplace=True)

df2['X3'].unique()

array([2., 1., 3., 4.])

- **X4:** estado civil (1=casado, 2=soltero, 3=otro). Nuevamente imputamos el valor de la moda a los valores faltantes.

In [37]:
# verificamos valores únicos en la columna
df2['X4'].unique() 

array([ 1.,  2.,  3.,  0., nan])

En este caso, el valor 0 no representa una categoria, por tanto lo que convertimos a nulo.

In [38]:
# sustituimos los valores 0 por NaN
for i in range(N):
    if df2.iloc[i, 4] == 0:
        df2.iloc[i, 4] = np.nan 

df2['X4'].unique()

array([ 1.,  2.,  3., nan])

In [40]:
# imputamos faltantes con la moda
x4mode = df2['X4'].mode()
df2['X4'].fillna(value = x4mode, inplace=True)

df2['X4'].unique()

array([1., 2., 3.])

- **X5:** edad del cliente (años)

In [41]:
# Revisamos las estadisticas de las edades
df2['X5'].describe()

count    29992.000000
mean        35.483862
std          9.218114
min         21.000000
25%         28.000000
50%         34.000000
75%         41.000000
max         79.000000
Name: X5, dtype: float64

En esta caso decidimos imputar los valores faltantes con la mediana (no se observa gran diferencia con la media).

In [42]:
# imputamos faltantes con la mediana
x5median = df2['X5'].median()
df2['X5'].fillna(value = x5median, inplace=True)

df2['X5'].isnull().values.any()

False

- **X6 - X11:** record de pago mensual de abril a septiembre (X6:septiembre, X7:agosto,...,X11:abril)

Valores: -1=pago a tiempo; 1=retraso 1 mes; 2=retraso 2 meses;...; 8=retraso 8 meses; 9=retraso 9 o mas meses.

In [43]:
# revisamos columnas X6 a X11
x6_x11 = df[['X6', 'X7', 'X8', 'X9', 'X10', 'X11']]
x6_x11

X6   X7   X8   X9  X10  X11
0      2.0  2.0 -1.0 -1.0 -2.0 -2.0
1     -1.0  2.0  0.0  0.0  0.0  2.0
2      0.0  0.0  0.0  0.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0  0.0
4     -1.0  0.0 -1.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...
29995  0.0  0.0  0.0  0.0  0.0  0.0
29996 -1.0 -1.0 -1.0 -1.0  0.0  0.0
29997  4.0  3.0  2.0 -1.0  0.0  0.0
29998  1.0 -1.0  0.0  0.0  0.0 -1.0
29999  0.0  0.0  0.0  0.0  0.0  0.0

[30000 rows x 6 columns]

Se observan valores de **-2.0** y **0** que no corresponden a ninguna categoría de estas columnas. Por lo tanto asignamos el valor *NaN* a todos los valores no permitidos. 

In [44]:
# Iteramos fila por fila de la columna X6 a la X11
for j in range(6):
    for i in range(N):
        if df2.iloc[i, 6+j] < -1:
            df2.iloc[i, 6+j] = np.nan 
        elif df2.iloc[i, 6+j] == 0:
            df2.iloc[i, 6+j] = np.nan
        elif df2.iloc[i, 6+j] > 9:
            df2.iloc[i, 6+j] = np.nan

In [45]:
# verificamos valores unicos 
print('X6: ', df2['X6'].unique())
print('X7: ', df2['X7'].unique())
print('X8: ', df2['X8'].unique())
print('X9: ', df2['X9'].unique())
print('X10: ', df2['X10'].unique())
print('X11: ', df2['X11'].unique())

X6:  [ 2. -1. nan  1.  3.  4.  8.  7.  5.  6.]
X7:  [ 2. nan -1.  3.  5.  7.  4.  1.  6.  8.]
X8:  [-1. nan  2.  3.  4.  6.  7.  1.  5.  8.]
X9:  [-1. nan  2.  3.  4.  5.  7.  6.  1.  8.]
X10:  [nan -1.  2.  3.  5.  4.  7.  8.  6.]
X11:  [nan  2. -1.  3.  6.  4.  7.  8.  5.]


Imputamos los nulos con el valor de la moda de cada columna.

In [46]:
# calculamos la moda
x6mode = df2['X6'].mode()
x7mode = df2['X7'].mode()
x8mode = df2['X8'].mode()
x9mode = df2['X9'].mode()
x10mode = df2['X10'].mode()
x11mode = df2['X11'].mode()

In [50]:
# imputamos valores
df2['X6'].fillna(x6mode, inplace=True)
df2['X7'].fillna(x7mode, inplace=True)
df2['X8'].fillna(x8mode, inplace=True)
df2['X9'].fillna(x9mode, inplace=True)
df2['X10'].fillna(x10mode, inplace=True)
df2['X11'].fillna(x11mode, inplace=True)

# verificamos
df2[['X6', 'X7', 'X8', 'X9', 'X10', 'X11']].isnull().values.any()

False

- **X12 - X17:** monto por pagar de abril a septiembre (X12:septiembre, X13:agosto,...,X17:abril)

In [51]:
# revisamos estadisticas
amnt= df2[['X12', 'X13', 'X14', 'X15', 'X16', 'X17']]
amnt.describe() 

X12            X13           X14            X15  \
count   29988.000000   29988.000000  2.998700e+04   29985.000000   
mean    51237.191210   49190.970555  4.702535e+04   43275.652326   
std     73646.425254   71184.560296  6.936086e+04   64345.500073   
min   -165580.000000  -69777.000000 -1.572640e+05 -170000.000000   
25%      3564.750000    2985.750000  2.667500e+03    2329.000000   
50%     22385.500000   21205.000000  2.008900e+04   19052.000000   
75%     67139.750000   64027.250000  6.018200e+04   54560.000000   
max    964511.000000  983931.000000  1.664089e+06  891586.000000   

                 X16            X17  
count   29983.000000   29990.000000  
mean    40324.493980   38881.135745  
std     60809.984983   59561.312967  
min    -81334.000000 -339603.000000  
25%      1763.500000    1256.250000  
50%     18107.000000   17081.000000  
75%     50213.000000   49208.250000  
max    927171.000000  961664.000000

Observamos montos negativos, los cuales tendremos que asumir como error de captura y los convertimos a monto positivo.

In [52]:
# usamos metodo abs para regresar solo valores positivos
for m in df2.iloc[:,12:18]:
    df2[m] = df2[m].abs()
 
# verificamos
amnt = df2[['X12', 'X13', 'X14', 'X15', 'X16', 'X17']]
amnt.describe()

X12            X13           X14            X15  \
count   29988.000000   29988.000000  2.998700e+04   29985.000000   
mean    51282.631386   49245.878251  4.708941e+04   43349.094981   
std     73614.789808   71146.584625  6.931739e+04   64296.043549   
min         0.000000       0.000000  0.000000e+00       0.000000   
25%      3596.750000    3055.000000  2.776000e+03    2400.000000   
50%     22393.500000   21234.500000  2.010900e+04   19068.000000   
75%     67207.250000   64049.500000  6.018650e+04   54589.000000   
max    964511.000000  983931.000000  1.664089e+06  891586.000000   

                 X16            X17  
count   29983.000000   29990.000000  
mean    40395.916719   39022.199500  
std     60762.560911   59468.986025  
min         0.000000       0.000000  
25%      1867.500000    1359.250000  
50%     18128.000000   17135.000000  
75%     50231.500000   49262.750000  
max    927171.000000  961664.000000

Debido a que se observan valores extremos (*outliers*), usamos la mediana para los valores nulos.

In [53]:
# calculamos la mediana
x12med = df2['X12'].median()
x13med = df2['X13'].median()
x14med = df2['X14'].median()
x15med = df2['X15'].median()
x16med = df2['X16'].median()
x17med = df2['X17'].median()

In [54]:
# imputamos valores
df2['X12'].fillna(x12med, inplace=True)
df2['X13'].fillna(x13med, inplace=True)
df2['X14'].fillna(x14med, inplace=True)
df2['X15'].fillna(x15med, inplace=True)
df2['X16'].fillna(x16med, inplace=True)
df2['X17'].fillna(x17med, inplace=True)

# verificamos
df2[['X12', 'X13', 'X14', 'X15', 'X16', 'X17']].isnull().values.any()

False

- **X18 - X23:** monto de pago anterior de abril a septiembre (X18:septiembre, X19:agosto,...,X23:abril)

In [55]:
# revisamos estadisticas
amnt2 = df2[['X18', 'X19', 'X20', 'X21', 'X22', 'X23']]
amnt2.describe() 

X18           X19            X20            X21  \
count   29992.000000  2.999100e+04   29992.000000   29989.000000   
mean     5662.945886  5.922489e+03    5225.623400    4827.252526   
std     16564.165089  2.304418e+04   17608.422625   15668.751975   
min         0.000000  0.000000e+00       0.000000       0.000000   
25%      1000.000000  8.355000e+02     390.000000     296.000000   
50%      2100.000000  2.009000e+03    1800.000000    1500.000000   
75%      5006.000000  5.000000e+03    4505.500000    4014.000000   
max    873552.000000  1.684259e+06  896040.000000  621000.000000   

                 X22            X23  
count   29989.000000   29995.000000  
mean     4800.297209    5216.259977  
std     15280.842069   17778.848359  
min         0.000000       0.000000  
25%       251.000000     118.000000  
50%      1500.000000    1500.000000  
75%      4033.000000    4000.000000  
max    426529.000000  528666.000000

En este caso no hay valores negativos por lo que procedemos a imputar valores nulos con la mediana.

In [56]:
# calculamos la mediana
x18med = df2['X18'].median()
x19med = df2['X19'].median()
x20med = df2['X20'].median()
x21med = df2['X21'].median()
x22med = df2['X22'].median()
x23med = df2['X23'].median()

In [57]:
# imputamos valores
df2['X18'].fillna(x18med, inplace=True)
df2['X19'].fillna(x19med, inplace=True)
df2['X20'].fillna(x20med, inplace=True)
df2['X21'].fillna(x21med, inplace=True)
df2['X22'].fillna(x22med, inplace=True)
df2['X23'].fillna(x23med, inplace=True)

# verificamos
df2[['X18', 'X19', 'X20', 'X21', 'X22', 'X23']].isnull().values.any()

False

Verificamos nuevamente que no existan columnas con valores nulos en el data frame:

In [58]:
df2.isnull().any() 

ID     False
X1     False
X2     False
X3     False
X4     False
X5     False
X6     False
X7     False
X8     False
X9     False
X10    False
X11    False
X12    False
X13    False
X14    False
X15    False
X16    False
X17    False
X18    False
X19    False
X20    False
X21    False
X22    False
X23    False
Y      False
dtype: bool

**Finalmente tenemos un *data frame* sin valores nulos:**

In [64]:
# data frame final:
print(df2.shape)

df2

(29997, 25)


ID      X1   X2   X3   X4    X5   X6   X7   X8   X9  ...      X15  \
0          1   20000  2.0  2.0  1.0  24.0  2.0  2.0 -1.0 -1.0  ...      0.0   
1          2  120000  2.0  2.0  2.0  26.0 -1.0  2.0  2.0  2.0  ...   3272.0   
2          3   90000  2.0  2.0  2.0  34.0  2.0  2.0  2.0  2.0  ...  14331.0   
3          4   50000  2.0  2.0  1.0  37.0  2.0  2.0  2.0  2.0  ...  28314.0   
4          5   50000  1.0  2.0  1.0  57.0 -1.0  2.0 -1.0  2.0  ...  20940.0   
...      ...     ...  ...  ...  ...   ...  ...  ...  ...  ...  ...      ...   
29995  29996  220000  1.0  3.0  1.0  39.0  2.0  2.0  2.0  2.0  ...  88004.0   
29996  29997  150000  1.0  3.0  2.0  43.0 -1.0 -1.0 -1.0 -1.0  ...   8979.0   
29997  29998   30000  1.0  2.0  2.0  37.0  4.0  3.0  2.0 -1.0  ...  20878.0   
29998  29999   80000  1.0  3.0  1.0  41.0  1.0 -1.0  2.0  2.0  ...  52774.0   
29999  30000   50000  1.0  2.0  1.0  46.0  2.0  2.0  2.0  2.0  ...  36535.0   

           X16      X17      X18      X19      X20     X21      X22     X23  \
0          0.0      0.0      0.0    689.0      0.0     0.0      0.0     0.0   
1       3455.0   3261.0      0.0   1000.0   1000.0  1000.0      0.0  2000.0   
2      14948.0  15549.0   1518.0   1500.0   1000.0  1000.0   1000.0  5000.0   
3      28959.0  29547.0   2000.0   2019.0   1200.0  1100.0   1069.0  1000.0   
4      19146.0  19131.0   2000.0  36681.0  10000.0  9000.0    689.0   679.0   
...        ...      ...      ...      ...      ...     ...      ...     ...   
29995  31237.0  15980.0   8500.0  20000.0   5003.0  3047.0   5000.0  1000.0   
29996   5190.0      0.0   1837.0   3526.0   8998.0   129.0      0.0     0.0   
29997  20582.0  19357.0      0.0      0.0  22000.0  4200.0   2000.0  3100.0   
29998  11855.0  48944.0  85900.0   3409.0   1178.0  1926.0  52964.0  1804.0   
29999  32428.0  15313.0   2078.0   1800.0   1430.0  1000.0   1000.0  1000.0   

         Y  
0      1.0  
1      1.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
29995  0.0  
29996  0.0  
29997  1.0  
29998  1.0  
29999  1.0  

[29997 rows x 25 columns]

### **Parte 3: Preparación de los datos** 

Con base en los resultados de tu libreta de Google Colab de la Parte 2 responde detalladamente las siguientes preguntas:

**1. ¿Qué datos considero más importantes? ¿Por qué?**

Considero que en esta primera etapa del análisis no podemos descartar la importancia de unas u otras variables, ya que desconocemos la correlación que puedan tener con la variable de salida.
Por otra parte, tomando en cuenta la descripción y el objetivo de la base de datos, en este caso deseamos comparar la exactitud del modelo para predecir la probabilidad de que un cliente cumpla o no con su pago crediticio. Considero importantes los datos de la variable de salida en la columna ‘Y’, ya que es el dato real que nos da la tendencia del comportamiento de los clientes.  

**2. ¿Se eliminaron o reemplazaron datos nulos? ¿Qué se hizo y por qué?**

En el ejercicio de limpieza se observó que en la columna ‘Y’ solamente había 3 entradas faltantes, por lo que decidí eliminar esas 3 filas en lugar de imputar un valor. Esto para dejar solamente valores reales en esta variable. 
El resto de los valores faltantes se reemplazaron de acuerdo con el siguiente razonamiento: 
- Para variables categóricas, por ejemplo, la columna ‘X2’ que representa el genero del cliente, se reemplazaron los faltantes por la categoría mas común, es decir la moda.  
- Para las variables numéricas, primero se analizó la distribución de los datos y se reemplazaron los faltantes de acuerdo con la tendencia central. Consideramos la mediana como una mejor opción que la media, ya que la media es más susceptible a valores extremos (outliers).     

**3. ¿Es necesario ordenar los datos para el análisis? Sí / No / ¿Por qué?**

Para poder trabajar con un modelo de aprendizaje supervisado, como es el caso de nuestra base de datos, es necesario que no existan datos faltantes y que tengan el formato adecuado. Por lo tanto, si es necesario ordenar y limpiar los datos previo al análisis.  En el sentido de tener que ordenar los registros para realizar operaciones no es necesario, ya que Pyhton lo maneja internamente. En este análisis solo tenemos los datos de una sola fuente, por lo que no requerimos consolidar o integrar datos de fuentes distintas.    

**4. ¿Existen problemas de formato que deban solucionar antes del proceso de modelado? Sí / No / Por qué?**

En esta base de datos el formato es adecuado, todos los valores incluyendo las variables categóricas están en tipo ‘float’, es decir números con decimales, y los valores faltantes (NaN) fueron imputados de igual manera con valores tipo 'float'. No se detectaron valores booleanos o de texto (string).  Al final de la limpieza los datos quedaron estructurados en un data frame adecuado para el proceso de modelado

**5. ¿Qué ajustes se realizaron en el proceso de limpieza de datos (agregar, integrar, eliminar, modificar registros (filas), cambiar atributos (columnas)?**

Principalmente se imputaron valores a los datos nulos, pero también se detectó que algunas columnas contenían valores no permitidos. Por ejemplo, en las columnas X6 a X11 con variables categóricas, los valores 0 y -2 no correspondían a ninguna categoría. En este caso, se cambiaron a valor nulo y se reemplazaron igual que el resto. 

Similarmente, en las columnas X12 a X17 se observaron valores negativos para variables que representan un monto de deuda. En este caso lo ideal sería investigar si existe alguna razón para colocar el monto negativo. Sin embargo al no contar con informacion adicional, se asumió como un error y se modificó el valor a positivo. Finalmemte, en la columna ‘Y’ se eliminaron filas con valor nulo, como lo menciono en la pregunta 2. Al final se eliminaron 3 filas del data frame, que representa el 0.01% del total de registros.   

_ _ _